const FIVE_MINUTES_MS = 300000;

enum EVENT_SOURCE {
  DISCORD = 'discord',
  ALEXA = 'alexa',
}

const DISCORD_ACTIONS = {
  MESSAGE_CREATE: 'messageCreate',
};

const DISCORD_EVENTS = {
  DISCORD_READY: 'DiscordReady',
  DISCORD_CONNECTION_ERROR: 'DiscordConnectionError',
  DISCORD_PROCESSING_ERROR: 'DiscordProcessingError',
  DISCORD_MESSAGE_CREATED: 'DiscordMessageCreated',
  DISCORD_INTERACTION_CREATED: 'DiscordInteractionCreated',
  DISCORD_INTERACTION_VALIDATED: 'DiscordInteractionValidated',
  DISCORD_INTERACTION_PROCESSED: 'DiscordInteractionProcessed',
  DISCORD_CREATED_MESSAGE: 'DiscordCreatedMessage',
  DISCORD_ENRICHED_MESSAGE: 'DiscordEnrichedMessage',
};

const OPENAI_EVENTS = {
  OPENAI_PROCESS_INPUT: 'OpenAIProcessInput',
  OPENAI_TEXT_QUERY: 'OpenAITextQuery',
  OPENAI_WEB_QUERY: 'OpenAIWebQuery',
};

const EXPRESS_EVENTS = {
  EXPRESS_RESPONSE_READY: 'ExpressResponseReady',
};

const EVENTS = {
  ERROR: 'error',
  PROCESS_ERROR: 'ProcessError',
  ...DISCORD_EVENTS,
  ...OPENAI_EVENTS,
  ...EXPRESS_EVENTS,
};

const DECISION_EVENTS = {
  DECISION_INPUT_PROCESSED: 'DecisionInputProcessed',
};

const SUMMARIZE_EVENTS = {
  SUMMARIZE_INPUT_PROCESSED: 'SummarizeInputProcessed',
};

const THINK_EVENTS = {
  THINK_INPUT_PROCESSED: 'ThinkInputProcessed',
};

const SPEAK_EVENTS = {
  SPEAK_INPUT_PROCESSED: 'SpeakInputProcessed',
};

const IGNORE_EVENTS = {
  IGNORE_INPUT_PROCESSED: 'IgnoreInputProcessed',
};

const CONTEXT_COMPOSER_EVENTS = {
  CONTEXT_COMPOSER_INPUT_PROCESSED: 'ContextComposerInputProcessed',
  CONTEXT_COMPOSER_AGENT_RESPONSE_PROCESSED: 'ContextComposerAgentResponseProcessed',
};

const MESSAGE_QUEUE_EVENTS = {
  MESSAGE_QUEUE_INPUT_RECEIVED: 'MessageQueueInputReceived',
};

const PIPELINE_ENTRY_POINT = 'EventsPipelineEntryPoint';
const PROCESS_AGENT_RESPONSE = 'EventsPipelineProcessAgentResponse';

const PIPELINE_EVENTS = {
  ...DECISION_EVENTS,
  ...SUMMARIZE_EVENTS,
  ...THINK_EVENTS,
  ...SPEAK_EVENTS,
  ...IGNORE_EVENTS,
  ...CONTEXT_COMPOSER_EVENTS,
  ...MESSAGE_QUEUE_EVENTS,
  PIPELINE_ENTRY_POINT,
  PROCESS_AGENT_RESPONSE,
};

const DECISION_ACTIONS = {
  IGNORE: 'IGNORE',
  THINK: 'THINK',
  SUMMARIZE: 'SUMMARIZE',
  SPEAK: 'SPEAK',
};

enum SPEAK_QUEUE_STATE {
  PENDING = 'PENDING',
  CLAIMED = 'CLAIMED',
  DONE = 'DONE',
};

export { SPEAK_QUEUE_STATE, DECISION_ACTIONS, FIVE_MINUTES_MS, DISCORD_ACTIONS, DISCORD_EVENTS, OPENAI_EVENTS, EVENTS, EVENT_SOURCE, PIPELINE_EVENTS };
