const {
  DISCORD_ENABLED,
  EXPRESS_ENABLED,

  DISCORD_TOKEN,
  DISCORD_ADMIN_ID,
  DISCORD_COMMAND_OVERRIDES,

  DISCORD_CHAT_HISTORY_CACHE,
  DISCORD_CHAT_HISTORY_CACHE_TTL,

  OPENAI_TEXT_MODEL,
  OPENAI_MCP_SERVERS,
  OPENAI_SYSTEM_PROMPT,

  PERPLEXITY_BASE_URL,
  PERPLEXITY_API_KEY,
  PERPLEXITY_MODEL,
  PERPLEXITY_SYSTEM_PROMPT,

  AWS_ALEXA_SKILL_ID,
} = process.env;

export {
  DISCORD_ENABLED,
  EXPRESS_ENABLED,
  DISCORD_TOKEN,
  DISCORD_ADMIN_ID,
  DISCORD_COMMAND_OVERRIDES,
  DISCORD_CHAT_HISTORY_CACHE,
  DISCORD_CHAT_HISTORY_CACHE_TTL,
  OPENAI_TEXT_MODEL,
  OPENAI_MCP_SERVERS,
  OPENAI_SYSTEM_PROMPT,
  PERPLEXITY_BASE_URL,
  PERPLEXITY_API_KEY,
  PERPLEXITY_MODEL,
  PERPLEXITY_SYSTEM_PROMPT,
  AWS_ALEXA_SKILL_ID,
};
