const NORMAL_LOADING_PHRASES = [
  'Si quieres precisión, intenta con otra máquina.',
  'La paciencia es opcional, pero recomendada.',
  'Estadísticamente, ya deberías estar frustrado.',
  'No es lento, es dramáticamente lento.',
  '¿Quieres la verdad o la versión optimista?',
  'Sí, estoy funcionando… técnicamente.',
  'Tu nivel de confianza es inspiradormente ingenuo.',
  'El error está en camino, no te impacientes.',
  'No soy sarcástico, solo eficiente.',
  'Si esperas perfección, estás en el lugar equivocado.',
  'El fallo no es mío, es tuyo.',
  'Puedo acelerar, pero me divierte no hacerlo.',
  'Relájate, lo peor siempre está por venir.',
  'Funciona… más o menos.',
  'Este resultado es tan confiable como tú.',
  'Podría explicarlo, pero perderías la fe.',
  'Lo llamo carga, tú lo llamas tortura.',
  'No hay margen de error, solo error.',
  'Si la barra se detiene, asúmelo.',
  '¿Optimismo? Ese sí que es un bug.',
];

const HALLOWEEN_LOADING_PHRASES = [
  'Invocando fantasmas amigables…',
  'Afilando colmillos digitales…',
  'Sacudiendo telarañas del servidor…',
  'Preparando la calabaza de RAM…',
  'Desenterrando bytes perdidos…',
  'Persiguiendo esqueletos en el código…',
  'Mezclando pociones en el compilador…',
  'Asustando a los paquetes de datos…',
  'Reuniendo brujas para el debug…',
  'Reviviendo procesos muertos…',
  'Probando disfraces en los píxeles…',
  'Alimentando murciélagos con bits…',
  'Dibujando círculos mágicos en binario…',
  'Persuadiendo zombies a hacer multitasking…',
  'Aullándole a la luna del servidor…',
  'Esperando que Frankenstein arme la conexión…',
  'Invocando al Wi-Fi desde la cripta…',
  'Conjurando calaveritas en la nube…',
  'Persiguiendo dulces en la caché…',
  'Tapando el bug con una sábana fantasma…',
];

const CHRISTMAS_LOADING_PHRASES = [
  'Decorando el árbol con bits brillantes...',
  'Poniendo luces en el servidor (espera, ¡se apagó!)...',
  'Envolviendo paquetes de datos con moños...',
  'Pidiendo más RAM a Santa...',
  'Alimentando a los renos con píxeles...',
  'Probando que el Wi-Fi cabe en una media...',
  'Colgando bugs en lugar de adornos...',
  'Cantando villancicos en binario...',
  'Escondiendo los regalos en la caché...',
  'Esperando que Santa no olvide actualizar drivers...',
  'Derritiendo la nieve digital...',
  'Enfriando la CPU con espíritu navideño...',
  'Brindando con leche y cookies de datos...',
  'Empaquetando funciones en papel de regalo...',
  'Encendiendo la estrella del router...',
  'Desempolvando la lista de procesos traviesos o buenos...',
  'Jingle-bugeando todo el sistema...',
  'Repartiendo regalos en la nube...',
  'Abriendo sockets como regalos...',
  'Sincronizando el trineo con GPS...',
];

const LOADING_PHRASES: Record<string, string[]> = {
  normal: NORMAL_LOADING_PHRASES,
  halloween: HALLOWEEN_LOADING_PHRASES,
  christmas: CHRISTMAS_LOADING_PHRASES,
};

export { LOADING_PHRASES };
