import { OPENAI_EVENTS } from './constants';

const COMMANDS_LIST = {
  GPT: 'gpt',
  GPT_WEB: 'gptweb',
};

const ROLE_AVAILABLE_COMMANDS = {
  OWNER: {
    [COMMANDS_LIST.GPT_WEB]: OPENAI_EVENTS.OPENAI_WEB_QUERY,
  },
  ADMIN: {
    [COMMANDS_LIST.GPT]: OPENAI_EVENTS.OPENAI_TEXT_QUERY,
    [COMMANDS_LIST.GPT_WEB]: OPENAI_EVENTS.OPENAI_WEB_QUERY,
  },
  USER: {
    [COMMANDS_LIST.GPT]: OPENAI_EVENTS.OPENAI_TEXT_QUERY,
  },
};

export { COMMANDS_LIST, ROLE_AVAILABLE_COMMANDS };
